parent_dir = "configs/abalone"
model_save_path = "ckpt/abalone"
sample_save_path = "sampled/abalone"
real_data_path = "Data/abalone"
task_type = "regression"
model_type = "mlp"
seed = 0

[model_params]
num_classes = 2
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    1024,
    2048,
    2048,
    1024,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
lr = 0.001809824563637657
weight_decay = 0.0
batch_size = 1028

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "mean"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 3340
batch_size = 1000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"